# azure-pipelines.yml
trigger:
  branches:
    include:
      - develop   # Run pipeline when code is pushed to main

pool:
  vmImage: 'windows-latest'   # Use Windows agent for .NET builds

variables:
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

    # inputs:
    #   packageType: 'sdk'
    #   version: '8.0.x'   # Specify .NET SDK version
    #   installationPath: $(Agent.ToolsDirectory)/dotnet

  # - script: dotnet restore
  #   displayName: 'Restore NuGet packages'

  # - script: dotnet build --configuration $(buildConfiguration)
  #   displayName: 'Build solution'

  # - script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  #   displayName: 'Run unit tests'

  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfiguration=true /p:PackageLocation=$(Build.ArtifactStagingDirectory)'
      platform: 'Any CPU'
      configuration: 'Release'
  - task: VSTest@2
    inputs:
      platform: 'Any CPU'
      configuration: 'Release'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
